; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
test_framework = googletest

[env:nano_33_iot]
lib_ldf_mode = chain+
platform = atmelsam
test_framework = googletest
board = nano_33_iot
framework = arduino
monitor_speed = 115200
lib_deps = 
	powerbroker2/SerialTransfer@^3.1.2
	Wire
	arduino-libraries/WiFiNINA@^1.8.14
	arduino-libraries/ArduinoMqttClient@^0.1.7
	arduino/Arduino Cloud Provider Examples@^1.2.1
	arduino-libraries/ArduinoBearSSL@^1.7.3
	thijse/ArduinoLog@^1.1.1
	arduino-libraries/Arduino_JSON@^0.2.0
	bblanchon/ArduinoJson@^6.21.4
